project:
  type: website

website:
  title: "The Delftia Project"
  site-url: "https://delftia.org"
  favicon: images/cropped-cropped-DelftiaLogo-e1594312941275-32x32.png

  navbar:
    logo: images/DelftiaLogo-e1594312941275.png
    logo-alt: "Delftia Project logo"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: news.qmd
        text: News
      - href: references.qmd
        text: References

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




